# Intrinsic parameters (only support pinhole atm)
size:
  width: 752
  height: 480
intrinsics:
  fx: 457.587
  fy: 456.134
  cx: 379.999
  cy: 255.238
distortion:
  k1: -0.28368365
  k2: 0.07451284
  p1: -0.00010473
  p2: -3.55590700e-05
  k3: 0